apiVersion: apps/v1
kind: Deployment
metadata:
  name: reveal-sec-prj-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 771196742746.dkr.ecr.us-east-1.amazonaws.com/reveal-sec-prj_nginx:latest
          ports:
            - containerPort: 80
