version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - internal
  php:
    image: php:fpm-alpine
    networks:
      - internal
